# Site
url: ""
baseurl: "/"
permalink: /:title/

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
